// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRf2PbpZ7IbpGkNXGWxC_EJM9z82SBamk',
    appId: '1:1072176325931:web:91e81dc4d27cc9af31116e',
    messagingSenderId: '1072176325931',
    projectId: 'oildatabase-781a4',
    authDomain: 'oildatabase-781a4.firebaseapp.com',
    databaseURL: 'https://oildatabase-781a4-default-rtdb.firebaseio.com',
    storageBucket: 'oildatabase-781a4.appspot.com',
    measurementId: 'G-QVKS3X18PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsBIQHQpmeyZ254RhjLeARLHgRqlTtKEE',
    appId: '1:1072176325931:android:3901d2d7d8c1b53431116e',
    messagingSenderId: '1072176325931',
    projectId: 'oildatabase-781a4',
    databaseURL: 'https://oildatabase-781a4-default-rtdb.firebaseio.com',
    storageBucket: 'oildatabase-781a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUSM7he0yIY5o7MGeo86gJuT84LKI3Bc',
    appId: '1:1072176325931:ios:d2e772445c1b5d9a31116e',
    messagingSenderId: '1072176325931',
    projectId: 'oildatabase-781a4',
    databaseURL: 'https://oildatabase-781a4-default-rtdb.firebaseio.com',
    storageBucket: 'oildatabase-781a4.appspot.com',
    androidClientId: '1072176325931-c4cg6g0e22b01tm06m5t7d8n136jrbfb.apps.googleusercontent.com',
    iosClientId: '1072176325931-uas9rjalu3po2nrps6824l3p3b00685c.apps.googleusercontent.com',
    iosBundleId: 'com.example.oilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAUSM7he0yIY5o7MGeo86gJuT84LKI3Bc',
    appId: '1:1072176325931:ios:d2e772445c1b5d9a31116e',
    messagingSenderId: '1072176325931',
    projectId: 'oildatabase-781a4',
    databaseURL: 'https://oildatabase-781a4-default-rtdb.firebaseio.com',
    storageBucket: 'oildatabase-781a4.appspot.com',
    androidClientId: '1072176325931-c4cg6g0e22b01tm06m5t7d8n136jrbfb.apps.googleusercontent.com',
    iosClientId: '1072176325931-uas9rjalu3po2nrps6824l3p3b00685c.apps.googleusercontent.com',
    iosBundleId: 'com.example.oilapp',
  );
}
