// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwIe1ZcwfThOH_BVY-ZirwrM-KXobbppc',
    appId: '1:691428496676:web:9e1ee02fad465531508fb1',
    messagingSenderId: '691428496676',
    projectId: 'globaloil-d853e',
    authDomain: 'globaloil-d853e.firebaseapp.com',
    storageBucket: 'globaloil-d853e.appspot.com',
    measurementId: 'G-GR20CQR8M5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrz2yJCdDbU46U_P_eW2CJD8rXHq6GyE',
    appId: '1:691428496676:android:1851ed28901f0760508fb1',
    messagingSenderId: '691428496676',
    projectId: 'globaloil-d853e',
    storageBucket: 'globaloil-d853e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6CBbfgNm7ZyqBo-I-rt3AyM6MEeJQY3A',
    appId: '1:691428496676:ios:8bf6f4066a852341508fb1',
    messagingSenderId: '691428496676',
    projectId: 'globaloil-d853e',
    storageBucket: 'globaloil-d853e.appspot.com',
    iosBundleId: 'com.example.oilapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6CBbfgNm7ZyqBo-I-rt3AyM6MEeJQY3A',
    appId: '1:691428496676:ios:8bf6f4066a852341508fb1',
    messagingSenderId: '691428496676',
    projectId: 'globaloil-d853e',
    storageBucket: 'globaloil-d853e.appspot.com',
    iosBundleId: 'com.example.oilapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwIe1ZcwfThOH_BVY-ZirwrM-KXobbppc',
    appId: '1:691428496676:web:40ddf81ecdec34ec508fb1',
    messagingSenderId: '691428496676',
    projectId: 'globaloil-d853e',
    authDomain: 'globaloil-d853e.firebaseapp.com',
    storageBucket: 'globaloil-d853e.appspot.com',
    measurementId: 'G-G1Q9CPBDGS',
  );
}
